#!/bin/bash

help() {
    echo "Usage: install-jvm -d|a <archive-location> -n <alias>"
    echo ""
    echo "(Download and) install a JVM from a tar.gz archive, updating references"
    echo "for the 'update-alternatives' and 'update-java-alternatives' tools automatically."
    echo ""
    echo "Due to the usage of the update-alternatives and update-java-alternative"
    echo "commands, elevated permissions are required to execute this program."
    echo ""
    echo "Mandatory arguments to long options are mandatory for short options too."
    echo "  -a, --archive          use existing tar archive at this location or download"
    echo "                         archive to this location if -d is also set"
    echo "                         mandatory if -d is not set, optional otherwise"
    echo "  -d, --download         download tar archive from this location"
    echo "                         mandatory if -a is not set, optional otherwise"
    echo "  -e, --extract-dir      extract tar contents to this temporary directory"
    echo "                         target directory must not contain any files"
    echo "  -h, -?, --help         brings up this help section"
    echo "  -j, --java-alt-dir     update-java-alternatives JDK directory"
    echo "                         only necessary if the default location was changed"
    echo "  -n, --name             alias for the update-java-alternatives tool"
    echo "                         mandatory"
    echo "  -t, --download-target  target name for the downloaded tar file"
    echo "                         -d must be set as well"
    echo "  -x, --debug            does not serve any purpose at the moment"
    echo "                         will display more debug information in the future"
    echo ""
    echo "Examples:"
    echo "  install-jvm -d https://download.java.net/java/GA/jdk19.0.2/fdb695a9d9064ad6b064dc6df578380c/7/GPL/openjdk-19.0.2_linux-x64_bin.tar.gz -n jdk19.0.2"
    echo "  install-jvm -d https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-22.3.1/graalvm-ce-java19-linux-amd64-22.3.1.tar.gz -n graalvm-ce-java19-22.3.1"
    echo ""
    echo "GitHub repository for the project: https://github.com/Visparu/unix-tools"
    echo "For questions or feature requests, please open an issue there."
}

# check for sudo permissions
if [ $(id -u) -ne 0 ]; then
    >&2 echo "Program must be executed with root privileges."
    >&2 echo ""
    help
    exit 100
fi

x=n d=n t=n a=n e=n n=n j=n
while [ $# -gt 0 ]; do
    case $1 in
        -x|--debug)
            x=y
            shift
            ;;
        -d|--download)
            d=y
            DOWNLOAD_LOCATION="$2"
            shift 2
            ;;
        -t|--download-target)
            t=y
            DOWNLOAD_TARGET="$2"
            shift 2
            ;;
        -a|--archive)
            a=y
            ARCHIVE_LOCATION="$2"
            shift 2
            ;;
        -e|--extract-dir)
            e=y
            EXTRACT_DIR="$2"
            shift 2
            ;;
        -n|--name)
            n=y
            ALTERNATIVE_NAME="$2"
            shift 2
            ;;
        -j|--java-alt-dir)
            j=y
            JAVA_ALTERNATIVE_DIR="$2"
            shift 2
            ;;
        -h|-?|--help)
            help
            exit 0
            ;;
        *)
            >&2 echo "Unknown parameter passed: $1"
            >&2 echo ""
            help
            exit 1
            ;;
    esac
done

# handle non-option arguments
if [[ $# -ne 0 ]]; then
    >&2 echo "$0: No unnamed parameter expected."
    >&2 echo ""
    help
    exit 2
fi

# check for required variables
if [ -z ${DOWNLOAD_LOCATION+x} ] && [ -z ${ARCHIVE_LOCATION+x} ]; then
    >&2 echo "A download location or an archive location is required (-d|--download or -a|--archive)."
    >&2 echo ""
    help
    exit 3
fi
if [ -z ${ALTERNATIVE_NAME+x} ]; then
    >&2 echo "An alternative name is required (-n|--name)."
    >&2 echo ""
    help
    exit 4
fi

# substitute defaults
if [ -z ${EXTRACT_DIR+x} ]; then
    EXTRACT_DIR=/tmp/install-jvm/extract
fi
if [ -z ${JAVA_ALTERNATIVE_DIR+x}]; then
    JAVA_ALTERNATIVE_DIR=/usr/lib/jvm
fi

# download JDK tar file
if [ ! -z ${DOWNLOAD_LOCATION+x} ]; then
    if [ -z ${ARCHIVE_LOCATION+x} ]; then
        ARCHIVE_LOCATION=$(basename $DOWNLOAD_LOCATION)
    fi
    wget $DOWNLOAD_LOCATION --quiet -O $ARCHIVE_LOCATION
    if [ ! -f $ARCHIVE_LOCATION ]; then
        >&2 echo "Download of JVM failed."
        >&2 echo ""
        exit 5
    fi
fi

# create extraction directory
mkdir -p $EXTRACT_DIR
if [ ! -z $(ls -A $EXTRACT_DIR) ]; then
    >&2 echo "Extract directory is not empty."
    >&2 echo ""
    help
    exit 6
fi

# extract JDK files
tar -xzf $ARCHIVE_LOCATION -C $EXTRACT_DIR

# delete archive if JDK was downloaded
if [ $d = "y" ]; then
    rm $ARCHIVE_LOCATION
fi

FULL_ALTERNATIVE_PATH=$JAVA_ALTERNATIVE_DIR/$ALTERNATIVE_NAME

# move JDK to java-alternatives directory
rm -rf $FULL_ALTERNATIVE_PATH
mv $EXTRACT_DIR/$(ls -A $EXTRACT_DIR) $FULL_ALTERNATIVE_PATH
if [ ! -d $FULL_ALTERNATIVE_PATH ]; then
    >&2 echo "Moving the JDK to the alternative path failed."
    >&2 echo ""
    help
    exit 7
fi

# remove extraction directory
rm -r $EXTRACT_DIR

# gather binary files for alternatives
BIN_DIRECTORY=$FULL_ALTERNATIVE_PATH/bin
BIN_FILES="$BIN_DIRECTORY/*"
JINFO_FILE=$JAVA_ALTERNATIVE_DIR/.$ALTERNATIVE_NAME.jinfo

# create .jinfo file
echo "name=$ALTERNATIVE_NAME" >$JINFO_FILE
echo "alias=$ALTERNATIVE_NAME" >>$JINFO_FILE
echo "priority=1000" >>$JINFO_FILE
echo "section=non-free" >>$JINFO_FILE
echo "" >>$JINFO_FILE
for BIN_FILE in $BIN_FILES
do
    BIN_FILE_BASENAME=$(basename $BIN_FILE)
    echo "jdk $BIN_FILE_BASENAME $BIN_FILE" >>$JINFO_FILE
done

# install alternatives
for BIN_FILE in $BIN_FILES
do
    BIN_FILE_BASENAME=$(basename $BIN_FILE)
    LINK=/usr/bin/$BIN_FILE_BASENAME
    update-alternatives --install $LINK $BIN_FILE_BASENAME $BIN_FILE 1000
done

update-java-alternatives --set $ALTERNATIVE_NAME
